### ISSUE TITLE
feature/user-name does not handle "" or whitespace

### ISSUE THREAD

**Issue by 8thDay** [chingu-coders/Voyage2-Turtles-09#10]
-Initial name entry handles the case where the user tries to submit an empty string, but allows them to enter just white-space.
-When the user clicks on their name in the greeting to edit it, the feature will accept an empty string or white-space.

I've just handled a similar issue in `feature/main-focus`, using regex to look for any input that wasn't white-space. My code seems to be doing the job, but please let me know if you find a more robust solution.

**Comment by DavidLarsKetch** [comment]
Thanks for pointing this out. That's a good thought to look for a regex. The difficulty will be that because it isn't an `<input>` field, white space is `&nbsp;`. So, I need to prevent cases where only `&nbsp;` is present.

**Comment by DavidLarsKetch** [comment]
Looking at the fix I just commited. Looks like the regex I'm using `/\w[^&nbsp;]/` doesn't allow for a string containing only the characters &, n, b, s, and/or p. This solution does not account for those edge cases, then.

Any thoughts on a different regex I could pass in?

**Comment by 8thDay** [comment]
This turned out to be a thornier issue than I had imagined. I hadn't considered that it isn't an `<input>`!

Strangely, it will allow me to enter the character & now, but not nbsp (or any combination of just those letters). I can even change my name to `&nbsp;` 😄 

I'm not currently seeing a solution, but I will take another look in the morning.

**Comment by 8thDay** [comment]
@DavidLarsKetch Nice! Your latest commit handles user-names which are "" or solely whitespace.
In addition, it prevents excessive spaces being used in names.
