### ISSUE TITLE
Greeting incorrect between midnight and 3am

### ISSUE THREAD

**Issue by 8thDay** [chingu-coders/Voyage2-Turtles-09#23]
Between midnight and 3am, user is greeted with "Good Afternoon".

**Comment by 8thDay** [comment]
Proposed solution: Change `else if` condition to `currentHour >= 12 && currentHour < 18`

I'm not making this change immediately, as it makes sense to wait until the latest PR is merged.

**Comment by 8thDay** [comment]
PR made :)

**Comment by DavidLarsKetch** [comment]
Looks good!
