### ISSUE TITLE
Congratulations message is displayed when background image has been showcased

### ISSUE THREAD

**Issue by 8thDay** [chingu-coders/Voyage2-Turtles-09#38]
When the page elements are made visible again, after showcasing the background image, the `main focus` congratulations message is displayed. The message should only display when the user marks the main focus as completed.

**Comment by DavidLarsKetch** [comment]
Working on this one now.

**Comment by DavidLarsKetch** [comment]
Issue resolved in `issue/37` since solution was essentially the same. Merging `issue/37` into `development` will also resolve this.
