### ISSUE TITLE
Find a solution to the limit on API calls at Edamam

### ISSUE THREAD

**Issue by reuben-jones** [chingu-coders/Voyage2-Turtles-09#43]
**Problem:** Edamam (the food API service we're using) has a limit on the number of calls we can make—5000/month and 5/minute.

_Suggestion 1_
Load _x_ number of recipes on the initial request. Then when the user tries to refresh the recipe, they don't put through a new request. This is an okay solution, but one issue would be that all of the recipes loaded would have the same search query and diet filter. eg. "chicken" and "low-fat". It would be weird for the user to keep getting the same type of recipes with every refresh.

_Suggestion 2_
Remove the reload button. This would only allow users to see one recipe per day. As it _is_ a recipe of the day feature, this doesn't seem so bad in theory. In practice however, the recipes are so random that there's a fair chance that the result will be something that the user doesn't like.

_Suggestion 3_
Build in user preferences (and remove reload button). Instead of a random recipe automatically loading, have the panel set up so that the initial view presents a selection of preference filters for the user to choose from. Eg. The first view shows a series of food types that the user can pick from. Eg. Chicken, Cow, Pig, Vegetables, Pasta, Stew, etc. The next section would allow the user to pick from a variety of diets, eg. balanced, low-sodium, paleo, etc. And the last would allow them to select additional health tags, such as gluten free, peanut free, etc.

**Comment by 8thDay** [comment]
How about a combination of all 3 suggestions?
Give the user a single, random recipe per day by default, but add a recipe preferences section to the settings. Then you could either display a single, custom recipe per day, or show the reload button and implement suggestion 1.

**Comment by reuben-jones** [comment]
Thanks @8thDay. I'm not sure that I like suggestion 1 anymore, but willing to give it a shot if you think it makes sense. I just don't like that the "reload" will only display results from the one search query—the UX seems confusing.

One solution to that could be something like: "Don't like this recipe? Try another [low-sodium]
 [chicken] search >". This would make it clear what kind of result they'll get, just in case they were hoping for a beef or vegetarian recipe instead. Could also provide a quick link to update settings.

Thoughts?

**Comment by 8thDay** [comment]
I was just brainstorming really, and you have a much better feel for UX than I do. But for the sake of completeness (and to appease my OCD), here are a couple of further thoughts;

Maybe you could add _"Based on your preferences"_ and a link to the settings, in case the user wants to change them?

One possible side effect of this could be that inquisitive people like myself would spend time trying to tweak their preferences, and actually burn through *more* API calls, which would be rather counter productive!

**Comment by reuben-jones** [comment]
Working on this now.

**Comment by reuben-jones** [comment]
I decided to leave the reload button there for now. If I keep getting notified about exceeding the API call limit I'll come back to this. Have given the user some preference settings so they're hopefully less likely to want to refresh the recipe.
