### ISSUE TITLE
Recipe panel needs default recipe when there is no internet connection

### ISSUE THREAD

**Issue by reuben-jones** [chingu-coders/Voyage2-Turtles-09#47]
![image](https://user-images.githubusercontent.com/1831818/32332261-46702a9c-bfa2-11e7-855b-70ea84815f6a.png)

It would help to have a recipe (or an array of recipes) to populate the recipe panel if there is no internet connection. Currently it looks a little barren.

**Comment by reuben-jones** [comment]
A recipe to add to the array: 
https://www.edamam.com/recipe/easy-bacon-wrapped-dates-0115a884dfaccad0e39d4173ec4de69b

Yes, it's bacon. But with DATES! So healthy!

**Comment by DavidLarsKetch** [comment]
Once #70 is merged & closed, this issue is resolved.
