### ISSUE TITLE
Nutrition data: total vs per serving

### ISSUE THREAD

**Issue by DavidLarsKetch** [chingu-coders/Voyage2-Turtles-09#48]
Currently, nutrition data is totaled across all servings and displayed as such. However, there is some ambiguity to the user as to whether that data is per serving or total. So, either:
1. Add and display the units of the data, e.g., "total"
2. Modify the data and display its units so that it is "per serving"

**Comment by reuben-jones** [comment]
Resolved by PR https://github.com/chingu-coders/Voyage2-Turtles-09/pull/51

**Comment by reuben-jones** [comment]
(Waiting on merge)
