### ISSUE TITLE
Settings Design: Closing the settings pane isn't entirely intuitive

### ISSUE THREAD

**Issue by reuben-jones** [chingu-coders/Voyage2-Turtles-09#53]
My usual behaviour for closing popups is to click outside the window, or click on some kind of close icon eg. "x". It took me a while to figure out that I needed to click on the settings cog again to close the panel.

Suggestion: Add a listener for clicking outside the pane, and/or a "close window" button.

**Comment by 8thDay** [comment]
Yes, I 100% agree. I've even tried clicking outside the panel myself to close it... and I wrote the thing!

**Comment by 8thDay** [comment]
@mrreubenjones Can you give it another try, when you get a moment. Hopefully the latest commit resolves this issue.
