### ISSUE TITLE
Error occurs when user deselects ALL the ingredient options

### ISSUE THREAD

**Issue by reuben-jones** [chingu-coders/Voyage2-Turtles-09#62]
When a user deselects all of the ingredients, an empty query is sent to Edamam on the next request.

Not sure of the best way to deal with this, some options: 
- display a message that not all ingredients can be deselected, 
- not allow the the last ingredient to be deselected 
- reset the ingredients back to "all"
- let the user deselect everything, but send some kind of general query (maybe one that searches based on source (eg. Jamie Oliver)

**Comment by 8thDay** [comment]
Random thoughts...

- I think I would find the 3rd suggestion, _reset the ingredients back to "all"_, extremely frustrating (particularly if I had just taken the time to deselect them, all in one go).
- Would the last alternative be confusing? If, say, I'd deselected all the options, then it popped up a recipe with one or more of those ingredients?
- Having all the ingredients highlighted when the extension first loads, and prompting the user to "Choose your favourite ingredients", could be confusing. Some numpty (ok... me!) might start clicking on icons thinking that they were selecting their favourites, when they were actually deselecting them!

**Comment by reuben-jones** [comment]
Thanks for the feedback Toni! Very helpful for thinking this through.

The solution I'll go with:
- Under the title, I'll add a quick explanation. Something like "Highlight ingredients to personalize your recipe of the day. If no ingredients are selected, a random recipe will be chosen for you."
- If all ingredients are deselected, leave the display deselected, but return results for all ingredients.

**Comment by reuben-jones** [comment]
Resolved with pull request https://github.com/chingu-coders/Voyage2-Turtles-09/pull/73.
