### ISSUE TITLE
Need to add credits for icons, Edamam API, etc

### ISSUE THREAD

**Issue by reuben-jones** [chingu-coders/Voyage2-Turtles-09#63]
Icons:
https://www.flaticon.com/packs/food-set-2/2

Recipe API:
https://developer.edamam.com/

What else?

**Comment by 8thDay** [comment]
@mrreubenjones I was just starting to review your code, and was asking about the icons, and whether we need to credit them! You beat me to it!

I've already added credits for Edamam, Unsplash and Forismatic to the settings panel. So I will add a credit for the icons in the same place. 

I've also added a Chingu credit, though I'm a little uncertain as to where it should link to.
