### ISSUE TITLE
Quote sometimes returns `undefined` after Chrome Storage is cleared

### ISSUE THREAD

**Issue by 8thDay** [chingu-coders/Voyage2-Turtles-09#80]
I've seen this error twice, but can't recreate it deliberately.
It happened, both times, after I cleared Chrome Storage in order to do some testing.

![151117 undefined quote](https://user-images.githubusercontent.com/12767893/32856356-7c6f042a-ca3c-11e7-85d6-48cb3204d580.JPG)

Quote text reads "undefined".
I didn't check the author last time, but this time the author is `Anonymous`.

**Comment by DavidLarsKetch** [comment]
Looks like we've had some name changes on properties - working on the fix now.

**Comment by DavidLarsKetch** [comment]
Issue should be resolved with merging & closing #83
