### ISSUE TITLE
Is there a way to make changes to the commit history?

### ISSUE THREAD

**Issue by 8thDay** [chingu-coders/Voyage2-Turtles-09#85]
We have removed our API keys from future commits, but they are still accessible in the commit history. Is there a way to remove them?

**Comment by reuben-jones** [comment]
Technically, yes. But it seems that you have to remove entire files, which in our case isn't really that practical, or worth it. 

Also, good to note that there is always a chance that your repo has been cloned or forked, in which case your data is permanently compromised. 

Read more about how to remove files from your repo history here:
https://help.github.com/articles/removing-sensitive-data-from-a-repository/

**Comment by reuben-jones** [comment]
My advice would be to simply change our keys. That way we don't lose the commit history, and when we look back on this project a few years (let's face it, months) from now, we can see how n00b we were, and laugh. Ha, ha, ha.

**Comment by 8thDay** [comment]
😆 Just six weeks on, and I'm already having facepalm moments... what _were_ we thinking! 🤣
