### ISSUE TITLE
Error when double clicking on time

### ISSUE THREAD

**Issue by 8thDay** [chingu-coders/Voyage2-Turtles-09#9]
https://github.com/chingu-coders/Voyage2-Turtles-09/blob/ab7dc6dd69b719baa2d5c3cbb90c600df7bbc323/js/script-clock.js#L47

I'm getting the following error when I double click on the time:
`Error in response to storage.get: TypeError: Cannot read property 'hour12' of undefined
    at Object.chrome.storage.sync.get [as callback] (chrome-extension://bcophjanoidfloajjdncffigbhnnnolo/js/script-clock.js:54:32)
    at HTMLElement.timeHTMLSelector.addEventListener (chrome-extension://bcophjanoidfloajjdncffigbhnnnolo/js/script-clock.js:47:27)`

It looks like the `timeSetting` variable hasn't been saved when the `get` call is made on line 47. Presumably because this is the first time I have run the feature.

**Comment by DavidLarsKetch** [comment]
@8thDay Pull my most recent commit & see if you're still getting the same error. If not, issue is closed.

**Comment by 8thDay** [comment]
@DavidLarsKetch That's working perfectly now. Nice job! 🐢  🎉
