### ISSUE TITLE
Todo list text can be difficult to read on some backgrounds

### ISSUE THREAD

**Issue by 8thDay** [chingu-coders/Voyage2-Turtles-09#90]
![151117 todo background too transparent](https://user-images.githubusercontent.com/12767893/32870313-3b5db3f0-ca73-11e7-98a4-d645fe551dd2.PNG)

**Comment by DavidLarsKetch** [comment]
:wave: I take full responsibility for this one - I changed @misomighty well-tested styling.

**Comment by misomighty** [comment]
Not sure i've you've already tinkered with the css but I went ahead and made the styling a little more consistent with the settings panel. So far all 3 issues have been resolved in the branch issue-82. @DavidLarsKetch
