### ISSUE TITLE
To-do and Settings panel consistency

### ISSUE THREAD

**Issue by reuben-jones** [chingu-coders/Voyage2-Turtles-09#92]
![image](https://user-images.githubusercontent.com/1831818/32898167-4212ff92-ca9c-11e7-9aa9-7f2369ba80cb.png)

I've noticed that the Settings panel is a little bit removed from the icon, and the little arrow thing (technical name) doesn't quite point at the cog. On the other hand, the To-do panel could perhaps give the todo link a little breathing room, and doesn't have a little arrow thing. The panel corners are also different.

**Suggestions:**
- Give to-do panel the same rounded corners as settings
- Give to-do panel a little more bottom padding (balanced with the whitespace around the other sides of the todo list)
- Give to-do panel a little arrow thing
- Match the settings panel external spacing to the to-do panel

**Comment by 8thDay** [comment]
![161117 little arrow thing](https://user-images.githubusercontent.com/12767893/32916708-da18b052-cb14-11e7-96d9-1c9f1443ac52.JPG)

My PR #94 addresses most of the points above, though I'm sure there is still plenty of room for further styling. See what you think, and feel free to change it if need be.
